changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - chore
    - title: Other Changes
      labels:
        - "*"
